name: BitQuest
version: 2.0
author: The BitQuest Dev Team
main: com.bitquest.bitquest.BitQuest
description: The BitQuest Open Source Project
commands:
  ban:
    description: "Adds player to the ban list"
    usage: "/ban <player>"
  banlist:
    description: "Prints the list of banned players"
    usage: "/banlist"
  butcher:
    description: "kills all entities in the current chunk"
    usage: "/butcher"
  clan:
    description: "used for creating, joining, operating clans"
    usage: "/clan <new|invite|kick|join|leave>"
  land:
    description: "Manage permissions for the land you're standing on"
    usage: "/land <claim|transfer|permissions>"
  maintenance:
    description: "Enables maintenance mode and stops players from joining the server"
    usage: "/maintenance <seconds>"
  profession:
    description: "(EXPERIMENTAL) choose a profession"
    usage: "/profession rogue"
  send:
    description: "sends bits to other player"
    usage: "/send <amount> <player>"
  spawn:
    description: "teleports to spawn"
    usage: "/spawn"
  transfer:
    description: "Sends your BitQuest wallet balance to an external address of your own"
    usage: "/transfer <amount> <bitcoin address, e-mail or username>"
  unban:
    description: "Removes player from the ban list"
    usage: "/unban <player>"
  spectate:
    description: "Allows moderators to spectate players' actions"
    usage: "/spectate <player>"
  mod:
    description: "Utility to add/remove/list moderators"
    usage: "/mod <add|remove|list>"
  emergencystop:
    description: "Stops the server cleanly in case of emergency"
    usage: "/emergencystop [reason]"
  killAllVillagers:
    description: "Kills all the villagers"
    usage: "/killAllVillagers"
  upgradewallet:
    description: "Transfer funds from an old (BQ2.0) wallet"
    usage: "/upgradewallet"
  faucet:
    description: "Get testnet coins (development mode only)"
    usage: "/faucet"
  wallet:
    description: "Displays your BitQuest wallet info"
    usage: "/wallet"
  crashtest:
    description: "Crashes the plugin on purpose, hell breaks loose. Don't try this at home"
    usage: "/crashtest"
  report:
    description: "Sends a report message to the moderators"
    usage: "/report <player> <reason>"
  donate:
    description: "Donate to BitQuest from your wallet"
    usage: "/donate <amount>"
  fixabandonland:
    description: "Fixes chunks with no owners that still have permissions"
    usage: "/fixabandonland [true|yes]"
  migrateclans:
    description: "Migrate clans to keep track of members"
    usage: "/migrateclans"
